language: cpp

compiler: gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install mpich2
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - cd ./bench/integral/ && make run
  - cd ../..
  - cd ./bench/primes/ && make run
  - cd ../..
  - cd ./bench/arraySum/ && make run

